first try. Sprint #9
k-onstantin/java-filmorate pull request #2
Opened 2023-03-10 01:12 UTC by k-onstantin

Реализована логика согласно ТЗ#9.

2023-03-10 20:23 UTC, mikita95 requested changes
Все сделано отлично. Нужно лишь поправить пару моментов

2023-03-10 20:23 UTC, mikita95 commented on HELP.md
> +# Getting Started
Этот файл - общий. Лучше заменить его на README.md и просто коротко описать проект

2023-03-10 20:23 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        this.validationService = new ValidationService();
Вы сделали `ValidationService` и `FilmStorage` - @Component, то есть они уже создались в контексте спринга. Не нужно создавать их вручную. Можно просто передать их через конструктор как аргументы и спринг сам их заинжектит.

2023-03-10 20:23 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +public class UserController {
Стоит еще добавить юнит-тесты на контроллеры

2023-03-12 14:27 UTC, k-onstantin commented
- Заменил HELP.md на README.md, добавил краткое описание проекта
- Исправил конструкторы контроллеров
- Добавил юнит-тесты для контроллеров

2023-03-13 15:19 UTC, merged